// Generated by Wrangler
// After adding bindings to `wrangler.jsonc`, regenerate this interface via `npm run cf-typegen`

interface Env {
  // No bound env vars needed — API key comes from request
}
